pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                bat 'dotnet restore' 
                bat 'dotnet build --no-restore' 
            }
        }     
        stage('Deliver') { 
            steps {
                bat 'dotnet publish SimpleWebApi --no-restore -o publish_output' 
            }
            post {
                success {
                    archiveArtifacts 'publish_output/*.*'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // Copy artifacts to deployment folder
                    bat 'xcopy /E /I /Y publish_output\\* "\\\\TSITINFAPPWS039\\pgeweb\\iv2\\"'
                }
            }
        }
    }
}