pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                bat 'dotnet restore' 
                bat 'dotnet build --no-restore' 
            }
        }     
        stage('Deliver') { 
            steps {
                bat 'dotnet publish SimpleWebApi --no-restore -o published' 
            }
            post {
                success {
                    archiveArtifacts 'published/*.*'
                }
            }
        }
    }
}